// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPFtZ0wl8VZTqNJ66l5-Tqm7PNh9sq8Ig',
    appId: '1:1033882305087:web:d0f4a104e719e565ceae8a',
    messagingSenderId: '1033882305087',
    projectId: 'nestifymega',
    authDomain: 'nestifymega.firebaseapp.com',
    storageBucket: 'nestifymega.firebasestorage.app',
    measurementId: 'G-H5LPRVYZLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP1z1YwjefTyBPMwhL-hoWD85b_01R8Rk',
    appId: '1:1033882305087:android:84a980ab046d58e6ceae8a',
    messagingSenderId: '1033882305087',
    projectId: 'nestifymega',
    storageBucket: 'nestifymega.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdplcwPl8eRNLb0i2SblneNzsn2Q7YIWs',
    appId: '1:1033882305087:ios:5351c747ff562df4ceae8a',
    messagingSenderId: '1033882305087',
    projectId: 'nestifymega',
    storageBucket: 'nestifymega.firebasestorage.app',
    iosBundleId: 'com.example.nestify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdplcwPl8eRNLb0i2SblneNzsn2Q7YIWs',
    appId: '1:1033882305087:ios:5351c747ff562df4ceae8a',
    messagingSenderId: '1033882305087',
    projectId: 'nestifymega',
    storageBucket: 'nestifymega.firebasestorage.app',
    iosBundleId: 'com.example.nestify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPFtZ0wl8VZTqNJ66l5-Tqm7PNh9sq8Ig',
    appId: '1:1033882305087:web:501d44519511a20fceae8a',
    messagingSenderId: '1033882305087',
    projectId: 'nestifymega',
    authDomain: 'nestifymega.firebaseapp.com',
    storageBucket: 'nestifymega.firebasestorage.app',
    measurementId: 'G-TWN4QJP8YZ',
  );
}
